# Generated by Django 5.2 on 2025-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sub_role',
            field=models.CharField(choices=[('individual', 'Individual'), ('restaurant', 'Restaurant'), ('grocery', 'Grocery Store')], max_length=20),
        ),
    ]
