# Generated by Django 5.2 on 2025-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0006_eventbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBooking',
            new_name='FoodBooking',
        ),
    ]
