# Generated by Django 5.2 on 2025-04-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0007_rename_eventbooking_foodbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_type',
            new_name='food_name',
        ),
    ]
