# Generated by Django 5.2 on 2025-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0008_rename_food_type_food_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbooking',
            name='qauntity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
