# Generated by Django 5.2 on 2025-04-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0009_foodbooking_qauntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodbooking',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
