# Generated by Django 5.2 on 2025-04-11 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0010_rename_qauntity_foodbooking_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbooking',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Donations.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='pickup_window',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='recipient_location',
            field=models.CharField(max_length=255),
        ),
    ]
