# Generated by Django 5.2 on 2025-04-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0011_foodbooking_food_foodbooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbooking',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donations.food'),
        ),
    ]
