# Generated by Django 5.2 on 2025-04-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0013_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='food_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Donations.foodbooking'),
        ),
    ]
