# Generated by Django 5.2 on 2025-04-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0016_foodbooking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='expiry_date',
        ),
    ]
